//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v14.0.7.0 (NJsonSchema v11.0.0.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

/* tslint:disable */
/* eslint-disable */
// ReSharper disable InconsistentNaming

export class ApiError implements IApiError {
  code!: string | undefined;
  message!: string | undefined;

  constructor(data?: IApiError) {
      if (data) {
          for (var property in data) {
              if (data.hasOwnProperty(property))
                  (<any>this)[property] = (<any>data)[property];
          }
      }
  }

  init(_data?: any) {
      if (_data) {
          this.code = _data["code"];
          this.message = _data["message"];
      }
  }

  static fromJS(data: any): ApiError {
      data = typeof data === 'object' ? data : {};
      let result = new ApiError();
      result.init(data);
      return result;
  }

  toJSON(data?: any) {
      data = typeof data === 'object' ? data : {};
      data["code"] = this.code;
      data["message"] = this.message;
      return data;
  }
}

export interface IApiError {
  code: string | undefined;
  message: string | undefined;
}